# Generated by Django 6.0.4 on 2026-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_allergens',
            field=models.CharField(blank=True, help_text='Содержит аллергены (через запятую: alcohol, fragrance, essential_oils, parabens)', max_length=500, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='product',
            name='solves_problems',
            field=models.CharField(blank=True, help_text='Какие проблемы решает (через запятую: acne, pigmentation, wrinkles, dehydration, redness)', max_length=500, verbose_name='Решаемые проблемы'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_skin_types',
            field=models.CharField(blank=True, help_text='Типы кожи, для которых подходит (через запятую: dry, oily, combination, normal, sensitive)', max_length=200, verbose_name='Подходит для типов кожи'),
        ),
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, choices=[('gel', 'Гель'), ('cream', 'Крем'), ('lotion', 'Лосьон'), ('serum', 'Сыворотка'), ('oil', 'Масло'), ('foam', 'Пенка')], max_length=50, verbose_name='Текстура'),
        ),
    ]
