# Generated by Django 6.0.4 on 2026-04-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_allergens_product_solves_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_type',
        ),
    ]
