# Generated by Django 6.0.4 on 2026-04-25 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'verbose_name': 'Рутина', 'verbose_name_plural': 'Рутины'},
        ),
        migrations.AddField(
            model_name='routine',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Утренняя'), ('evening', 'Вечерняя')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='goal',
            field=models.CharField(choices=[('hydration', 'Увлажнение'), ('anti_acne', 'Против акне'), ('anti_age', 'Антивозрастной'), ('sensitive', 'Для чувствительной кожи'), ('cleansing', 'Очищение')], max_length=50),
        ),
        migrations.AlterField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
    ]
