# Generated by Django 6.0.4 on 2026-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_routine_options_routine_time_of_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='goal',
            field=models.CharField(choices=[('hydration', 'Увлажнение'), ('anti_acne', 'Против акне'), ('anti_age', 'Антивозрастной'), ('sensitive', 'Для чувствительной кожи'), ('cleansing', 'Очищение'), ('custom', 'Пользовательская')], max_length=50),
        ),
    ]
