# Generated by Django 6.0.4 on 2026-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_alter_routine_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='time_of_day',
        ),
        migrations.AlterField(
            model_name='routine',
            name='goal',
            field=models.CharField(choices=[('custom', 'Пользовательская')], default='custom', max_length=50),
        ),
    ]
