# Generated by Django 6.0.4 on 2026-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_remove_routine_time_of_day_alter_routine_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Утренняя')], default='morning', max_length=20),
        ),
    ]
