# Generated by Django 6.0.4 on 2026-05-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'verbose_name': 'Тема форума', 'verbose_name_plural': 'Темы форума'},
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Эмодзи или символ', max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимо'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.forumtopic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимо'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.forumpost', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
