# Generated by Django 6.0.4 on 2026-05-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumpost', verbose_name='Ответ на'),
        ),
    ]
