# Generated by Django 6.0.4 on 2026-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_forumpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Иконка'),
        ),
    ]
