# Generated by Django 6.0.4 on 2026-05-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forumcategory_icon'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='views_count',
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_images', to='wagtailimages.image', verbose_name='Изображение'),
        ),
    ]
