# Generated by Django 6.0.4 on 2026-05-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_forumtopic_views_count_forumtopic_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='wagtailimages.image', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.forumpost', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Изображение сообщения',
                'verbose_name_plural': 'Изображения сообщений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_images', to='wagtailimages.image', verbose_name='Изображение')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.forumtopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Изображение темы',
                'verbose_name_plural': 'Изображения темы',
                'ordering': ['order'],
            },
        ),
    ]
