# Generated by Django 6.0.4 on 2026-04-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('dry', 'Сухая'), ('oily', 'Жирная'), ('combination', 'Комбинированная'), ('normal', 'Нормальная'), ('sensitive', 'Чувствительная')], max_length=20, null=True)),
                ('problems', models.CharField(blank=True, max_length=500)),
                ('age_range', models.CharField(blank=True, choices=[('under20', 'До 20'), ('20-30', '20-30'), ('30-45', '30-45'), ('45plus', '45+')], max_length=20, null=True)),
                ('allergies', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
